### ISSUE TITLE
snmpwalk 取端口状态报错问题

### ISSUE THREAD

**Issue by xudong-wen** [gaochao1/swcollector#12]
Hi，你好，
我在使用时遇到如下问题，请您帮忙查看下：
交换机：华为CE6850交换机 
error log : 2016/06/07 17:31:02 ifstat_snmpwalk.go:16: 10.6.0.130 Recovered in ListIfStats_SnmpWalk runtime error: slice bounds out of range

查看代码后发现是这一样包的错
ifstatus := ifstatus_string[(len(ifstatus_string) - 2):(len(ifstatus_string) - 1)]
请问这一样的作用是为了更好的兼容吗？
我的交换机取出来的数据为1或2，len后截取为 ifstatus_string[-1:0] 这样会panic

**Comment by freedomkk-qfeng** [comment]
可能是snmpwalk的版本问题？我测试的时候snmpwalk对于ifOperStatus的返回值是这样的。
IF-MIB::ifOperStatus.436231168 = INTEGER: up(1)
IF-MIB::ifOperStatus.436231680 = INTEGER: up(1)
IF-MIB::ifOperStatus.436232192 = INTEGER: down(2)
所以去截取了倒数第二位

下一个版本考虑把snmpwalk的开关放在配置文件里，大家自己选用gosnmp去拉还是snmpwalk

**Comment by xudong-wen** [comment]
能否加入CRC和Discard的数据收集，在对网络质量监控时非常有用。

```
ifHCOuntCRCOid               = ".1.3.6.1.2.1.2.2.1.14"
ifHCOuntDiscardOid       = ".1.3.6.1.2.1.2.2.1.19"
```

**Comment by freedomkk-qfeng** [comment]
考虑将来增加

**Comment by xudong-wen** [comment]
有大概的时间预期吗？

**Comment by zzlyzq** [comment]
@xudong-wen  兄弟， 我们目前也需要Discard的数据，但是根据我们的调研，有几点需要注意：
1. CRC错误的OID，我们根据OID查到是 ifInErrors
2. ifHCOuntDiscardOid 该OID对应的Name是 ， ifOutDiscards (.1.3.6.1.2.1.2.2.1.19)

另外， 根据我们的观察， 
1. 网络交换机这块，我们又发现 入方向有 Error，但是Discard全是0. 
2. 服务器这块， 我们发现入方向有Drop，但是没有Error.

而且，本身这种丢包对于大数据的 实时或者离线来说， 丢包会造成 TCP丢包， 会导致服务器TcpExt.TCPTimeouts， 默认5次后会到 TcpExt.TCPAbortOnTimeout，而这个会造成上层应用有反应，比如，wget 会中断，下载文件不完整; 对于实时系统，我们当前怀疑 丢包会造成 Storm任务延迟增大， 不过这个还在进一步论证中， 所以正好需要swcollection对丢包和错包进行监控。

**Comment by freedomkk-qfeng** [comment]
error基本是链路层问题，校验有错误
outdiscard的丢包可以和OutQlen的队列长度来一起看，是否网络产生拥赛
这些考虑下个版本增加进去
