### ISSUE TITLE
是否可以新增 端口丢包统计

### ISSUE THREAD

**Issue by zzlyzq** [gaochao1/swcollector#15]
兄弟：

```
你好。非常感谢该插件给我们监控实时和离线集群接入和核心交换机带来的便利，爱不释手。
```

   最近随着业务量的增加，虽然交换机的上联带宽还有50%的剩余带宽，但是我们怀疑交换机设备在数据传输中造成的丢包影响到了上层应用的稳定性，尤其是实时集群。

   当前该插件还不支持网络设备丢包检查，希望兄弟可以添加该支持。

再次感谢。

**Comment by zzlyzq** [comment]
兄弟，经过几天努力，已经完成了Discards和Errors的支持。 我还在进一步验证。

**Comment by freedomkk-qfeng** [comment]
可以得话，提交个PR~~

**Comment by championdot** [comment]
您好，为什么swcollector监控通过snmp监控网络设备的端口流量断断续续的，前提是falcon和mrtg 部署在同一台机器上，mrtg就不存在这样的问题，困惑啊

**Comment by zzlyzq** [comment]
@championdot  兄弟， mrtg默认5分钟采集一次，falcon是一分钟， 而且我觉得重点是不是在 采集的时常这块， 如果是华为的交换机， 貌似 snmp很慢， 适当调整下试试。

这种情况我没有遇到过， juniper和锐捷的 我们在用，没有遇到啥问题。
