### ISSUE TITLE
ping报错

### ISSUE THREAD

**Issue by Bryan-Yan** [gaochao1/swcollector#17]
我直接ping交换机的管理口是通的，但监控日志报下面的错，传上来的值一直都是-1.。。请问这种报错是怎么回事啊？

swping.go:40: 10.127._._ dial ip4:icmp 10.127._._: operation not permitted

另外再问下一台普通的主机（4C8G）能监控多少台交换机呢？

**Comment by freedomkk-qfeng** [comment]
看上去是权限问题，要 root 用户执行哦
swcollector的资源占用不大，主要限制还是交换机的snmp返回速度，思科之类快一些，华为之类慢一些。一般单个实例监控50-100台左右问题不大。
