### ISSUE TITLE
open-falcon portal中无法添加交换机机器作为报警

### ISSUE THREAD

**Issue by modeyang** [gaochao1/swcollector#2]
```
"switch":{                                                                                                                        
  "enabled": true,
  "ipRange":[
        "172.31.*.*/ 32" 
  ],   
```

.......
 "heartbeat": {
        "enabled": true,
        "addr": "127.0.0.1:6030",
        "interval": 60,
        "timeout": 1000
    },
    "transfer": {
        "enabled": true,
        "addr": "127.0.0.1:8433",
        "interval": 60,
        "timeout": 1000
    }
这是我的cfg.json配置
在添加host的框中添加交换机IP后，提示no such host, 但是在dashboard中有该交换机的监控数据。
而且open-falcon 自带的agent所处的机器是能够添加到portal的。
不知道是什么问题，求解？ 谢谢了

**Comment by gaochao1** [comment]
参考https://github.com/open-falcon/portal/issues/3

**Comment by gaochao1** [comment]
参考文档：
http://book.open-falcon.com/zh/install_from_src/hbs.html
Portal的数据库中有一个host表，维护了公司所有机器的信息，比如hostname、ip等等。这个表中的数据通常是从公司CMDB中同步过来的。但是有些规模小一些的公司是没有CMDB的，那此时就需要手工往host表中录入数据，这很麻烦。于是我们赋予了HBS第一个功能：agent发送心跳信息给HBS的时候，会把hostname、ip、agent version、plugin version等信息告诉HBS，HBS负责更新host表。

开启heartbeat可自动更新host表
