### ISSUE TITLE
snmp v3

### ISSUE THREAD

**Issue by thelstcn** [gaochao1/swcollector#22]
什么时候支持snmp v3协议获取？

**Comment by macaty** [comment]
OpenFalcon-SuitAgent 可以先用这个，支持V3的，也是参照这里的代码

**Comment by lgy5** [comment]
我有个临时的方法，OpenFalcon-SuitAgent试了下不好使，很臃肿

cd $GOPATH/src/github.com/gaochao1/
git clone https://github.com/gaochao1/sw
git clone https://github.com/gaochao1/swcollector
git clone https://github.com/gaochao1/gosnmp


cd $GOPATH/src/github.com/gaochao1/sw
vim ifstat_snmpwalk.go
将
out, err := CmdTimeout(timeout, "snmpwalk", "-v", "2c", "-c", community, ip, oid)
改为
out, err := CmdTimeout(timeout, "snmpwalk", "-v", "3", "-u", "user", "-a", "MD5", "-A", community, ip, oid)

cd $GOPATH/src/github.com/gaochao1/swcollector/
go get ./...
chmod +x control
rm falcon-swcollector
./control build 生成 falcon-swcollector

之后配置文件community为v3的密码，使用gosnmp为false

**Comment by lgy5** [comment]
暂时没有其他的好办法了，我这个很多写死了，不会go。。
