### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by macaty** [gaochao1/swcollector#28]
2017/04/25 06:13:09 swping.go:41: 192.168.1.1 lookup 192.168.1.1: too many open files
2017/04/25 06:13:09 swping.go:41: 192.168.1.2 lookup 192.168.1.2: too many open files
2017/04/25 06:13:09 swping.go:41: 192.168.1.3 lookup 192.168.1.3: too many open files
2017/04/25 06:13:09 swping.go:41: 192.168.1.4 lookup 192.168.1.4: too many open files
2017/04/25 06:13:09 swping.go:41: 192.168.1.5 lookup 192.168.1.5: too many open files
2017/04/25 06:13:09 swping.go:41: 192.168.1.6 lookup 192.168.1.6: too many open files
2017/04/25 06:15:22 rpc.go:44: dial 192.168.43.94:161:8433 fail: dial tcp 192.168.43.94:161:8433: socket: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp: lookup 192.168.1.1: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp: lookup 192.168.1.2: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp 192.168.1.3:161: socket: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp: lookup 192.168.1.4: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp: lookup 192.168.1.5: too many open files
2017/04/25 06:15:18 swmem.go:40: Error establishing connection to host: dial udp: lookup 192.168.1.6: too many open files

**Comment by freedomkk-qfeng** [comment]
ulimit -a
检查下 open files 句柄上限。
