### ISSUE TITLE
希望添加端口流量百分比

### ISSUE THREAD

**Issue by xudong-wen** [gaochao1/swcollector#30]
在配置报警的时候，使用带宽需要根具不同的交换机端口绑定不同的模板。如果能添加百分比，可以根具不同的业务区分不同的报警阀值，方便配置。所以希望添加带宽百分比上报。

**Comment by freedomkk-qfeng** [comment]
v4 版本已经增加
switch.if.InSpeedPercent
switch.if.OutSpeedPercent
