### ISSUE TITLE
能否增加收集的主机列表从数据库中读取，并把每次ping检测的结果统计到数据库对应的主机上去？

### ISSUE THREAD

**Issue by hel2o** [gaochao1/swcollector#34]
根据你的代码，我加了下把每次swping之后都去操作一次mysql数据库把这个主机的相关信息如ping的次数，失败次数，当前ping的延时等信息记录到mysql当中，这样对这台主机就可以做些其它的数据分析。但我不会写GO，加完后运行几个小时后，进程就报错了。。。也不知道什么原因。

**Comment by wangxinan1981** [comment]
2017/07/18 16:06:04 collector.go:74: INFO : Send metrics to transfer running in the background. Process time : 100.13773ms Send metrics : 8
2017/07/18 16:06:04 var.go:79: <= <Total=8, Invalid:6, Latency=0ms, Message:ok>
2017/07/18 16:06:48 swifstat.go:97: UpdateIfStats start. The number of concurrent limited to 1000. IP addresses number is 2
2017/07/18 16:06:48 swifstat.go:99: get snmp message by gosnmp
2017/07/18 16:06:54 ifstat.go:420: 10.17.255.228 1.3.6.1.2.1.31.1.1.1.6 Error reading from UDP: read udp 10.19.247.239:56558->10.17.255.228:161: i/o timeout

2017/07/18 16:06:54 ifstat.go:420: 134.80.66.145 1.3.6.1.2.1.31.1.1.1.6 Error reading from UDP: read udp 10.19.247.239:57661->134.80.66.145:161: i/o timeout

2017/07/18 16:06:54 ifstat.go:420: 10.17.255.228 1.3.6.1.2.1.31.1.1.1.10 Error reading from UDP: read udp 10.19.247.239:59462->10.17.255.228:161: i/o timeout

2017/07/18 16:06:54 ifstat.go:420: 134.80.66.145 1.3.6.1.2.1.31.1.1.1.10 Error reading from UDP: read udp 10.19.247.239:51320->134.80.66.145:161: i/o timeout

2017/07/18 16:06:54 ifstat.go:420: 134.80.66.145 1.3.6.1.2.1.31.1.1.1.1 Error reading from UDP: read udp 10.19.247.239:47045->134.80.66.145:161: i/o timeout

2017/07/18 16:06:54 ifstat.go:420: 10.17.255.228 1.3.6.1.2.1.31.1.1.1.1 Error reading from UDP: read udp 10.19.247.239:34115->10.17.255.228:161: i/o timeout

2017/07/18 16:07:00 ifstat.go:420: 134.80.66.145 1.3.6.1.2.1.31.1.1.1.15 Error reading from UDP: read udp 10.19.247.239:56622->134.80.66.145:161: i/o timeout

2017/07/18 16:07:00 ifstat.go:420: 10.17.255.228 1.3.6.1.2.1.31.1.1.1.15 Error reading from UDP: read udp 10.19.247.239:47996->10.17.255.228:161: i/o timeout

2017/07/18 16:07:00 swifstat.go:343: UpdateIfStats complete. Process time 11.512736182s. Number of active ip is 2
2017/07/18 16:07:00 swifstat.go:347: AliveIp: 0 10.17.255.228
2017/07/18 16:07:00 swifstat.go:347: AliveIp: 1 134.80.66.145

请问这个错误是什么原因? 交换机是 思科的N7K和H3的12504

**Comment by hel2o** [comment]
这是你的交换机SNMP信息设置不对

**Comment by wangxinan1981** [comment]
请问交换机侧如何配置呢？我们这边已经把snmp打开了

 

发件人: hel2o [mailto:notifications@github.com] 
发送时间: 2017年7月18日 16:34
收件人: gaochao1/swcollector
抄送: wangxinan1981; Comment
主题: Re: [gaochao1/swcollector] 能否增加收集的主机列表从数据库中读取，并把每次ping检测的结果统计到数据库对应的主机上去？ (#34)

 

这是你的交换机SNMP信息设置不对
