### ISSUE TITLE
建议添加H3C低端交换机版本为 Software Version 3.10

### ISSUE THREAD

**Issue by hel2o** [gaochao1/swcollector#37]
最新的版本V4.0.6无法收集这个较旧的交换机内存和CPU信息
CPU:  1.3.6.1.4.1.2011.6.1.1.1.2 Gauge32
MEM: 1.3.6.1.4.1.2011.10.2.6.1.1.1.1.8.20 Integer
func getH3CHWcpumem 这个函数在采取 这个版本的MEM时的method要改为get方式
看是否把getH3CHWcpumem函数多加一个参加传一个method进去

**Comment by freedomkk-qfeng** [comment]
给个交换机的型号和版本吧，我尽量找个环境测试下

**Comment by hel2o** [comment]
Hangzhou H3C Comware Platform Software, Software Version 3.10, Release R2211P07
H3C S2126-EI
Copyright(c) 2004-2011 Hangzhou H3C Tech. Co.,Ltd. All rights reserved.

**Comment by hel2o** [comment]
新版本的收集交换机的CPU和内存，看日志是有收集到呀 但在dashboard却看不到这些counter
![0z d t m4 6zogo54ml7a0](https://user-images.githubusercontent.com/14226648/29237297-fd2b46f8-7f4d-11e7-84b2-a33e1619cf32.png)

**Comment by freedomkk-qfeng** [comment]
这不科学，看看 graph 的数据库表里进没进数据，更新下 graph 的索引试试
https://book.open-falcon.org/zh_0_2/distributed_install/task.html

**Comment by hel2o** [comment]
好的，能问下v0.2版本的open-falcon如何更新索引 没有了task模块后。

**Comment by freedomkk-qfeng** [comment]
找不到测试机~
你可以直接修改测试后，发个 PR 过来吗
