### ISSUE TITLE
收集交换机内存和CPU时若设备类型不在设置的范围内会出现上报的endpoint名为空的情况

### ISSUE THREAD

**Issue by hel2o** [gaochao1/swcollector#38]
这种情况会造成上报给transfer时出现Invalid，所以建议在swcpu.go swmem.go的第28行增加一个对ip是否存在做一个判断

> 		if swCpu.Ip !="" {
> 			L = append(L, GaugeValueIp(time.Now().Unix(), swCpu.Ip, "switch.CpuUtilization", swCpu.CpuUtil))
> 		}

**Comment by freedomkk-qfeng** [comment]
确实，应该处理一下。之后修复

**Comment by freedomkk-qfeng** [comment]
已 fix
