### ISSUE TITLE
如何获取交换机中仅需要的端口？

### ISSUE THREAD

**Issue by CastroKKK** [gaochao1/swcollector#39]
你好：
请教下，我监控的核心交换端口太多，数量太大。但我实际并不需要监控这么多，并且全部监控会有udp I/O 部分接口超时 等问题会极大影响效率导致断图。
所以我如何配置可以做到仅获取部分端口？
谢谢。求指导。

**Comment by freedomkk-qfeng** [comment]
暂时不支持
