### ISSUE TITLE
采集思科N7K相关问题

### ISSUE THREAD

**Issue by SaltedFishChili** [gaochao1/swcollector#40]
hi，
   现在是采集思科N7K，上面接口全部是万兆，目前出的图全部是10G，并不是实际使用结果。请问下有解放方案吗？感谢;)

**Comment by freedomkk-qfeng** [comment]
万兆接口出来10G，我觉得并没有问题啊。。

**Comment by SaltedFishChili** [comment]
@freedomkk-qfeng 该问题已解决，谢谢。目前实测来看，falcon出图比实际时间晚五分钟，请问是sw本身上报时间晚吗？
