### ISSUE TITLE
堆叠交换机获取不全

### ISSUE THREAD

**Issue by lgy5** [gaochao1/swcollector#46]
作者您好，
我们是5个交换机合并为一个交换机使用，1/0/1-60 ，2/0/1-30 ， 3/0/1-30， 4/0/1-30 有这么多口
但是只获取到了1/0/1-60 ，2/0/1-30，日志也没有其他报错，不知道哪里的问题，谢谢
版本4.0.6.3

![qq 20180116181858](https://user-images.githubusercontent.com/12881911/34983897-fce51684-fae9-11e7-9abb-05da0ecd18e1.png)

**Comment by freedomkk-qfeng** [comment]
不应该呀，看截图似乎是 chart 或者 screen 里。应该是 dashboard 里表的上限，太多一次进图的话，会被截断。
可以看看在 dashboard 的 counter 的搜索中能搜到其他接口吗？

**Comment by lgy5** [comment]
dashboard 没有找到，我开了debug，日志里面也只有这些口，稍微有点多，采集方式是snmpwalk会有影响吗
[1.log](https://github.com/gaochao1/swcollector/files/1638150/1.log)

**Comment by lgy5** [comment]
cd $GOPATH/src/github.com/gaochao1/sw
vim ifstat_snmpwalk.go
将
out, err := CmdTimeout(timeout, "snmpwalk", "-v", "2c", "-c", community, ip, oid)
改为
out, err := CmdTimeout(timeout, "snmpwalk", "-v", "3", "-u", "user", "-a", "MD5", "-A", community, ip, oid)


修改了这个，临时支持下snmpv3，其他没有改，所以我只能用snmpwalk
