### ISSUE TITLE
snmp采集服务器指标

### ISSUE THREAD

**Issue by Crow07** [gaochao1/swcollector#47]
swcollector可以采集服务器的指标吗，通过snmp和自定义oid。

是不是只要snmp可以获取的指标，就可以用swcollector去采集。

测试报错：
2018/01/26 14:58:32 cfg.go:138: read config file: cfg.json successfully
2018/01/26 14:58:32 hostcfg.go:51: read hostconfig file: ./hosts.json successfully
2018/01/26 14:58:32 http.go:68: listening :1990
2018/01/26 14:58:32 swifstat.go:149: UpdateIfStats start. The number of concurrent limited to 1000. IP addresses number is 1
2018/01/26 14:58:32 swifstat.go:151: get snmp message by gosnmp
2018/01/26 14:58:37 ifstat.go:459: 172.31.6.112 1.3.6.1.2.1.31.1.1.1.6 Error reading from UDP: read udp 172.31.6.113:47978->172.31.6.112:161: i/o timeout

2018/01/26 14:58:37 ifstat.go:459: 172.31.6.112 1.3.6.1.2.1.31.1.1.1.10 Error reading from UDP: read udp 172.31.6.113:51990->172.31.6.112:161: i/o timeout

2018/01/26 14:58:37 ifstat.go:459: 172.31.6.112 1.3.6.1.2.1.31.1.1.1.1 Error reading from UDP: read udp 172.31.6.113:55929->172.31.6.112:161: i/o timeout

2018/01/26 14:58:37 ifstat.go:459: 172.31.6.112 1.3.6.1.2.1.31.1.1.1.15 Error reading from UDP: read udp 172.31.6.113:56109->172.31.6.112:161: i/o timeout

2018/01/26 14:58:37 swifstat.go:402: UpdateIfStats complete. Process time 5.83268415s. Number of active ip is 1
2018/01/26 14:58:37 swifstat.go:406: AliveIp: 0 172.31.6.112
2018/01/26 14:58:43 swcpu.go:43: Error reading from UDP: read udp 172.31.6.113:57453->172.31.6.112:161: i/o timeout

2018/01/26 14:58:49 swmem.go:43: Error reading from UDP: read udp 172.31.6.113:49271->172.31.6.112:161: i/o timeout

2018/01/26 14:58:50 collector.go:74: INFO : Send metrics to transfer running in the background. Process time : 100.561342ms Send metrics : 1
2018/01/26 14:58:50 var.go:96: <= <Total=1, Invalid:0, Latency=0ms, Message:ok>

用snmpwalk命令测试是没问题的

**Comment by freedomkk-qfeng** [comment]
应该可以采的才对。看看是不是 snmp 版本 v2c 的，以及 community 正不正确

**Comment by Crow07** [comment]
搞定了，是community没配对
