### ISSUE TITLE
2018/02/08 14:00:51 rpc.go:44: dial 127.0.0.1:8433 fail: dial tcp 127.0.0.1:8433: getsockopt: connection refused

### ISSUE THREAD

**Issue by tianshuangkun** [gaochao1/swcollector#51]
![_20180208140139](https://user-images.githubusercontent.com/33189205/35957890-d707e54e-0cd8-11e8-863b-57b0e716802a.png)

**Comment by freedomkk-qfeng** [comment]
transfer 的接收地址要配 falcon 的 transfer 地址。就和 falcon 的 agent 一样

**Comment by tianshuangkun** [comment]
为什么刚开始的时候并没有数据显示，而过了一会又有数据显示了，如下所示：
![_20180209195238](https://user-images.githubusercontent.com/33189205/36026670-1a97e980-0dd3-11e8-85cd-22655cd06ff0.png)
当刷新之后，又没有了数据，如下所示：
![_20180209195151](https://user-images.githubusercontent.com/33189205/36026721-49a3bfc4-0dd3-11e8-8344-019849b78583.png)

还有安装这个agent之后，获取的数据打向了哪里，是transfer中配置的地址吗，我还需要安装open-falcon吗，换成其他的接收数据的组件可以吗
