### ISSUE TITLE
对于交换机整体的进出口流量统计

### ISSUE THREAD

**Issue by modeyang** [gaochao1/swcollector#6]
请问swcollector对于交换机整体的进出口流量能进行统计吗？ 
现在只能看到单个端口的进出口流量、或者通过sum方法进行累加。
如果有，是哪个counter？ 谢谢。

**Comment by freedomkk-qfeng** [comment]
暂时木有此类统计

**Comment by modeyang** [comment]
但是我们利用zabbix是能获取到的每个交换机的总进出口流量，也是通过snmp, OID是有的. 可以测试下。

**Comment by freedomkk-qfeng** [comment]
总进出口流量是指所有端口的进出口流量之和，背板交换的流量么?我一时没找到oid，能提供一些oid来测试一下不。交换机型号，oid

**Comment by modeyang** [comment]
@freedomkk-qfeng  确认了下，确实没有有关oid能进行整个内部交换机端口的总流量，但是应该每个交换机都会有一个对外通讯的端口，例如switch.if.Out/ifIndex=103,ifName=Eth-Trunk0 这个端口，就会有整个交换机的总进出口对外的流量。当然每个公司的设置的端口不一样，具体要和网络部门的设置。 谢谢。

**Comment by KeithTt** [comment]
居然没有。。。
