### ISSUE TITLE
希望能够新增对a10 thunder930设备的内存、磁盘使用率的支持

### ISSUE THREAD

**Issue by w8589167** [gaochao1/swcollector#74]
下方提供了a10的oid
另外有几点小建议：
1：希望在后续的版本中，加入多团体名的支持，当前只支持单个团体名，如遇到不同团体名的需要复制整个文件夹，修改配置后启用新实例
2：希望在后续版本中，加入用户可配置的，对多个指标的自定义计算，组合成新指标的功能，便于在一些厂商并未提供直接oid指标，需要通过其他指标间接计算出来的情况
3：希望在后续版本中，加入指标的单位自定义，如百分比，M，G等
4：希望在后续版本中，
![image](https://user-images.githubusercontent.com/29417610/84723894-55b5a680-afb9-11ea-974d-373fa0fe0174.png)能将指标和oid放在一个数组里，这样在需要添加多条自定义oid时，无需再次复制上面的ip信息，简化了配置文件
[](url)

---------------------------------------------930 oid---------------------------------------------------
Total memory：.1.3.6.1.4.1.22610.2.4.1.2.1.0
Used memory：.1.3.6.1.4.1.22610.2.4.1.2.2.0
Free Disk Space：.1.3.6.1.4.1.22610.2.4.1.4.2.0
Total Disk Space：.1.3.6.1.4.1.22610.2.4.1.4.1.0

**Comment by freedomkk-qfeng** [comment]
[4.1.2](https://github.com/gaochao1/swcollector/releases/tag/4.1.2)
A10 的 cpu/mem 现在可以内置获取了。

配置方面的动静比较大，以后大版本调整的时候尝试优化吧

指标的单位定义，指标的计算，可能更适合由 n9e/open-falcon 在监控服务端计算，可以给 n9e/open-falcon 提个 issue 推动将来支持哈。插件采集侧简单一点比较好

**Comment by w8589167** [comment]
十分感谢大佬支持
