### ISSUE TITLE
新版本Agent Version 4.3.0与夜莺V3的问题

### ISSUE THREAD

**Issue by u31s** [gaochao1/swcollector#77]
1、发现活跃交换机数只能有20个，但我手工批量导入了40台
2、通过在夜莺V3中“导入新的交换机，删除旧的交换机”反复验证，仍是20个活跃交换机数
3、并且将之前手工导入的Linux和Windows主机也捞取过来，主机和交换机的总数仍然只是20台
4、导入夜莺的交换机，但在swcollector中未显示的交换机，在夜莺中看不到data
![swcollector-error1](https://user-images.githubusercontent.com/19942704/96663904-43db7a00-1384-11eb-94ef-2eb6af3f7aef.png)

手工重启过多次

**Comment by freedomkk-qfeng** [comment]
4.3.1 已修复这个问题

**Comment by u31s** [comment]
> 4.3.1 已修复这个问题

神速，可以了，谢谢
