### ISSUE TITLE
新版本Agent Version 4.3.1，运行一段时间后，活跃交换机数量为0

### ISSUE THREAD

**Issue by u31s** [gaochao1/swcollector#78]
正在体验夜莺V3的监控看图，突然就没有任何数据，查看swcollector页面，发现活跃交换机数变为 0
1、没有变动过任何配置
2、活跃交换机数变为 0，夜莺中的交换机均没有数据
3、restart 多次sw-collector，仍为0，包括删除重新配置

不知道哪里出了问题，是否有log可以查看

**Comment by freedomkk-qfeng** [comment]
看下 swcollector 配置的 node 节点和夜莺里挂在设备的节点是否一致？

**Comment by u31s** [comment]
1、一致的，我新搭了环境（sw-collector 4.3.0及4.3.1及夜莺V3）测试还是一样，是不是4.3的版本有问题
2、后使用sw-collector 4.2.1版本的，将cfg.json配置文件中的transfer的端口改为：8009就可以
3、之前4.2.1和夜莺V2版本的配合的很好，没有什么问题

**Comment by freedomkk-qfeng** [comment]
1. 用 4.3.1 ，在已经导入过交换机的情况下，用 iprange 来配置应该也是可以的。4.3 增加的主要是通过n9e接口来自动获取待监控的 endpoint。
2. 尝试在swcollector 的服务器上 curl 下接口试试。x-user-token 用 swcollector 里配置的 token，{id} 替换为 swcollector 里配置的节点 id。看下什么返回
```
curl -H "x-user-token: xxxxxxxx" http://n9ev3.example.com/api/rdb/node/{id}/resources
```

**Comment by u31s** [comment]
正常，夜莺升级到最新版就可以了，谢谢
