### ISSUE TITLE
V3版本获取IP地址字段的问题

### ISSUE THREAD

**Issue by corepbr** [gaochao1/swcollector#79]
前端页面中ident字段英文标识，而V3版本通过ident字段获取交换机IP地址。感觉不是很好理解。既然导入资产的时候已经有了IP字段，为何不通过通过IP字段获取设备IP地址。

**Comment by freedomkk-qfeng** [comment]
2个原因
1. 因为目前夜莺里，ip 的位置在资产的模块里（ams），而监控时我们获取的待监控的交换机列表要根据资源树上的节点来查，也就是 rdb 里，这里目前是只有 ident 的。要获取 ip 的话得根据 ident 再去 ams 里查一次
2. 数据上报的时候，endpoint 是根据 ident 的标识来上报监控数据的，所以如果确实 ident 和 ip 不一致，那么这里根据 ip 监控以后，需要再转换为 ident 作为 endpoint 去上报。这就得内部暂存下这两者的关系~~

所以就是太麻烦了。。。交换机就默认规定用 ip 做 ident 吧，简单一点

**Comment by corepbr** [comment]
明白了 感谢解答。
